main/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from . import views

app_name = "main"

urlpatterns = [
    path("", views.home , name="home"),
    path("search-results", views.search, name="search"),
    path("term_condition", views.term_condition , name="term_condition"),
    path("police_prive", views.police_prive , name="police_prive"),


    path("index2", views.index2 , name="index2"),
    path("index3", views.index3 , name="index3"),
    path("index4", views.index4 , name="index4"),
    path("coming-soon", views.coming_soon , name="coming-soon"),
    path("about", views.about , name="about"),
    path("contacts", views.contacts , name="contacts"),
    path("author-single", views.authorsingle , name="author-single"),
    path("help", views.help , name="help"),
    path("pricing-tables", views.pricingtables , name="pricing-tables"),
    path("booking-single", views.bookingsingle , name="booking-single"),
    path("dashboard", views.dashboard , name="dashboard"),
    path("blog2", views.blog2 , name="blog2"),
    path("blog-single", views.blogsingle , name="blog-single"),
    path("dashboard-add-listing", views.dashboardaddlisting , name="dashboard-add-listing"),
    path("error-page", views.errorpage , name="error-page"),
    path("invoice", views.invoice , name="invoice"),
    path("blog", views.blog , name="blog"),
    path("listing-single", views.listingsingle , name="listing-single"),
    path("listing-single2", views.listingsingle2 , name="listing-single2"),
    path("listing-single3", views.listingsingle3 , name="listing-single3"),
    path("listing-single4", views.listingsingle4 , name="listing-single4"),
    path("listing", views.listing, name="listing"),
    path("listing2", views.listing2, name="listing2"),
    path("listing3", views.listing3, name="listing3"),
    path("listing4", views.listing4, name="listing4"),
    path("listing6", views.listing6, name="listing6"),
    path("room1", views.room1, name="room1"),
    path("room2", views.room2, name="room2"),
    path("room3", views.room3, name="room3"),
    path("dashboard-listing-table", views.dashboardlistingtable , name="dashboard-listing-table"),
    path("dashboard-password", views.dashboardpassword, name="dashboard-password"),
    path("dashboard-review", views.dashboardreview , name="dashboard-review"),
    path("dashboard-add-listing", views.dashboardaddlisting , name="dashboard-add-listing"),









   






   
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"

urlpatterns = [
    path("create/", views.RoomCreateView.as_view(), name="create"),
    path("host-list/", views.RoomHostListView.as_view(), name="host-list"),
    path("list/", views.RoomListView.as_view(), name="list"),
    path("<int:pk>", views.RoomDetailView.as_view(), name="detail"),
    path("<int:pk>/edit/", views.RoomUpdateView.as_view(), name="edit"),
    path("<int:pk>/delete", views.RoomDeleteView.as_view(), name="delete_room"),
    path('book-room/<int:pk>/', views.book_room, name='book_room'),

    path("<int:pk>/photo-list", views.RoomPhotosView.as_view(), name="photo-list"),
    path("<int:pk>/photos/add/", views.AddPhotoView.as_view(), name="add-photo"),
    path("<int:room_pk>/photos/<int:photo_pk>/delete/", views.delete_photo, name="delete-photo"),
    path("<int:room_pk>/photos/<int:photo_pk>/edit/", views.EditPhotoView.as_view(), name="edit-photo")
    
    # path("search/", views.search, name="search"),
]

sank/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from main import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns



def trigger_error(request):
    division_by_zero = 1 / 0



urlpatterns = [
    # path('admin/', admin.site.urls),
    path("", include("main.urls")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("lists/", include("lists.urls", namespace="lists")),
    path(os.environ.get("ADMIN_URL", "admin/"), admin.site.urls),
    path("sentry-debug/", trigger_error),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from . import managers


class TimeStampedModel(models.Model):

    """ Time Stamped Model """

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    objects = managers.CustomModelManager()

    class Meta:
        abstract = True

main/forms.py
# forms.py
from django import forms


class SearchForm(forms.Form):
    city = forms.CharField(required=False)
    guests = forms.IntegerField(required=False)
    check_in = forms.DateField(required=False)
    check_out = forms.DateField(required=False)

    

rooms/forms.py
from django import forms
from django_countries.fields import CountryField
from . import models


class SearchForm(forms.Form):

   
    room_type = forms.ModelChoiceField(
        required=False, empty_label="Any kind", queryset=models.RoomType.objects.all()
    )
    prix_par_nuit = forms.IntegerField(required=False)
    prix_par_semaine = forms.IntegerField(required=False)
    prix_par_mois = forms.IntegerField(required=False)
    nombre_de_chambres = forms.IntegerField(required=False)
    nombre_de_lits = forms.IntegerField(required=False)
    nombre_de_douche = forms.IntegerField(required=False)
    agrement = forms.ModelMultipleChoiceField(
        required=False,
        queryset=models.Amenity.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )
    facilités = forms.ModelMultipleChoiceField(
        required=False,
        queryset=models.Facility.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )


class CreatePhotoForm(forms.ModelForm):
    class Meta:
        model = models.Photo
        fields = ("caption", "file")

    def save(self, pk, *args, **kwargs):
        photo = super().save(commit=False)
        room = models.Room.objects.get(pk=pk)
        photo.room = room
        photo.save()


class CreateRoomForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(CreateRoomForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "custom-form"
            visible.field.widget.attrs["placeholder"] = " "
        
    class Meta:
        model = models.Room
        fields = (
            "nom",
            "description",
            "prix_par_nuit",
            "prix_par_semaine",
            "prix_par_mois",
            "caution",
            "adresse",
            "nombre_de_lits",
            "nombre_de_chambres",
            "nombre_de_douche",
            "room_type",
            "agrement",
            "facilités",
            "reglements",
            "video",
        )
        labels = {
            "nom": "Titre",
            "description": "Description",
            "prix_par_nuit": "Prix par nuit (xof)",
            "prix_par_semaine": "Prix par semaine (xof)",
            "prix_par_mois": "Prix par mois (xof)",
            "caution":"Caution",
            "adresse": "Adresse",
            "agrement": "Commodités",
            "facilités": "Installations",
            "reglements": "règles de la maison",
            "nombre_de_lits": "Nombre de lits",
            "nombre_de_chambres": "chambres",
            "room_type": "Type",
            "video": "Vidéo de presentation",
            "nombre_de_douche": "Douches",

        }

    

main/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from main.forms import SearchForm
from rooms.models import Room


# Create your views here.
def coming_soon(request):
    
    return render(request, "coming-soon.html")


def term_condition(request):
    
    return render(request, "term_&_condition.html")


def police_prive(request):
    
    return render(request, "police_prive.html")


def home(request):
    rooms = Room.objects.all().order_by("-created")[:9]
    
    return render(request, "index.html", locals())



def search(request):
    if request.method == 'GET':
        form = SearchForm(request.GET)
        if form.is_valid():
            room_type = form.cleaned_data.get('room_type')
            guests = form.cleaned_data.get('guests')
            when = form.cleaned_data.get('main-input-search')

            # Perform search logic for Room model
            rooms = Room.objects.all()
            if room_type:
                rooms = rooms.filter(room_type__name__icontains=room_type)
            if guests:
                rooms = rooms.filter(guests=guests)
            # Add more filtering logic as needed (e.g., when, check_out)

            

            return render(request, 'search_results.html', {
                'room_type': room_type,
                'rooms': rooms,
            })

    # If form is invalid or method is not GET
    return render(request, 'search_results.html')






def index2(request):
    
    return render(request, "index2.html")



def index3(request):
    
    return render(request, "index3.html")


def index4(request):
    
    return render(request, "index4.html")




def errorpage(request):
    
    return render(request, "404.html")


def about(request):
    
    return render(request, "about.html")


def contacts(request):
    
    return render(request, "contacts.html")


def invoice(request):
    
    return render(request, "invoice.html")


def authorsingle(request):
    
    return render(request, "author-single.html")


def help(request):
    
    return render(request, "help.html")


def pricingtables(request):
    
    return render(request, "pricing-tables.html")


def bookingsingle(request):
    
    return render(request, "booking-single.html")


def dashboard(request):
    
    return render(request, "dashboard.html")



def blog2(request):
    
    return render(request, "blog2.html")



def blogsingle(request):
    
    return render(request, "blog-single.html")


def dashboardaddlisting(request):
    
    return render(request, "dashboard-add-listing.html")



def blog(request):
    
    return render(request, "blog.html")


def listingsingle(request):
    
    return render(request, "listing-single.html")


def listingsingle2(request):
    
    return render(request, "listing-single2.html")


def listingsingle3(request):
    
    return render(request, "listing-single3.html")


def listingsingle4(request):
    
    return render(request, "listing-single4.html")


def listing(request):
    
    return render(request, "listing.html")


def listing2(request):
    
    return render(request, "listing2.html")


def listing3(request):
    
    return render(request, "listing3.html")


def listing4(request):
    
    return render(request, "listing4.html")


def listing5(request):
    
    return render(request, "listing5.html")


def listing6(request):
    
    return render(request, "listing6.html")


def room1(request):
    
    return render(request, "rooms/room1.html")


def room2(request):
    
    return render(request, "rooms/room2.html")


def room3(request):
    
    return render(request, "rooms/room3.html")

def dashboardaddlisting(request):
    
    return render(request, "dashboard-add-listing.html")


def dashboardlistingtable(request):
    
    return render(request, "dashboard-listing-table.html")


def dashboardpassword(request):
    
    return render(request, "dashboard-password.html")


def dashboardreview(request):
    
    return render(request, "dashboard-review.html")

rooms/views.py
from urllib.parse import urlencode
from django.http import Http404
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (
    TemplateView,
    CreateView,
    DetailView,
    UpdateView,
    DeleteView,
    ListView,
    FormView,
)
from rooms.forms import CreatePhotoForm, CreateRoomForm
from rooms.models import Room, Photo, RoomType
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.shortcuts import render, redirect, reverse








# -------------------------- ROOMS -------------------#

# CREATE
class RoomCreateView(LoginRequiredMixin, CreateView):
    model = Room
    form_class = CreateRoomForm
    template_name = "room_create.html"
    success_url = reverse_lazy("rooms:host-list")
    

    def form_valid(self, form):
        form.instance.host = self.request.user.client
        print("success")
        return super(RoomCreateView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(RoomCreateView, self).get_context_data(**kwargs)
        return context
    

# LIST
class RoomHostListView(ListView):
    model = Room
    context_object_name = "rooms"
    template_name = "room_list.html"
    

    def get_queryset(self):
        return Room.objects.filter(host=self.request.user.client).order_by(
            "-created"
        )

    def get_context_data(self, **kwargs):
        context = super(RoomHostListView, self).get_context_data(**kwargs)
        
        # Add the total_rooms count to the context
        context["total_rooms"] = Room.objects.filter(host=self.request.user.client).count()
        return context
    
    
class RoomListView(ListView):
    model = Room
    paginate_by = 30
    context_object_name = "rooms"
    template_name = "listing.html"
    

    def get_queryset(self):
        return Room.objects.all().order_by("-created")

    def get_context_data(self, **kwargs):
        context = super(RoomListView, self).get_context_data(**kwargs)
        return context



def room_category(request, slug):
    category = RoomType.objects.get(slug=slug)
    room = Room.objects.filter(room_type=category)


    return render(request, "room_category.html", locals())



# DETAIL
class RoomDetailView(DetailView):
    model = Room
    context_object_name = "room"
    template_name = "room_detail.html"

    


def book_room(request, pk):
    room_url = request.build_absolute_uri(reverse('rooms:detail', kwargs={'pk': pk}))
    message = f"Salut, je suis intéressé par cet appartement: {room_url}"
    
    # Define the recipient number
    recipient_number = '22893716116'  # Replace with the recipient's phone number
    
    # Construct the WhatsApp URL with recipient number and message
    whatsapp_params = {
        'text': message,
        'phone': recipient_number
    }
    whatsapp_url = f"https://api.whatsapp.com/send?{urlencode(whatsapp_params)}"
    
    return redirect(whatsapp_url)


# UPDATE
class RoomUpdateView(LoginRequiredMixin, UpdateView):
    model = Room
    form_class = CreateRoomForm
    template_name = "room_edit.html"
    success_url = reverse_lazy("rooms:host-list")
    

    def get_context_data(self, **kwargs):
        context = super(RoomUpdateView, self).get_context_data(**kwargs)
        return context
    

# DELETE
class RoomDeleteView(LoginRequiredMixin, DeleteView):
    model = Room
    success_url = reverse_lazy("rooms:host-list")
    template_name = "room_confirm_delete.html"

# -------------------------- ROOMS PHTOS -------------------#


class RoomPhotosView(LoginRequiredMixin, DetailView):

    model = Room
    template_name = "room_photo_list.html"

    def get_object(self, queryset=None):
        room = super().get_object(queryset=queryset)
        if room.host.pk != self.request.user.client.pk:
            raise Http404()
        return room


def delete_photo(request, room_pk, photo_pk):
    user = request.user.client
    try:
        room = Room.objects.get(pk=room_pk)
        if room.host.pk != user.pk:
            messages.error(request, "Can't delete that photo")
        else:
            Photo.objects.filter(pk=photo_pk).delete()
            messages.success(request, "Photo deleted")
        return redirect(reverse("rooms:photo-list", kwargs={"pk": room_pk}))
    except Room.DoesNotExist:
        return redirect(reverse("main:home"))


class EditPhotoView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = Photo
    template_name = "room_photo_edit.html"
    pk_url_kwarg = "photo_pk"
    success_message = "Photo Updated"
    fields = ("caption",)

    def get_success_url(self):
        room_pk = self.kwargs.get("room_pk")
        return reverse("rooms:photo-list", kwargs={"pk": room_pk})


class AddPhotoView(LoginRequiredMixin, FormView):

    template_name = "room_photo_create.html"
    fields = ("caption", "file")
    form_class = CreatePhotoForm

    def form_valid(self, form):
        pk = self.kwargs.get("pk")
        form.save(pk)
        messages.success(self.request, "Photo Uploaded")
        return redirect(reverse("rooms:photo-list", kwargs={"pk": pk}))

main/templates/rooms/room1.html
{% extends "index.html" %}
{% load static %}
{% block content %}

<!--ajax-modal-wrap -->
<div class="ajax-modal-wrap fl-wrap">
    <div class="ajax-modal-close"><i class="fal fa-times"></i></div>
    <!--ajax-modal-item-->
    <div class="ajax-modal-item fl-wrap">
        <div class="ajax-modal-media fl-wrap">
            <img src="images/gal/1.jpg" alt="">
            <div class="ajax-modal-title">
                <div class="section-title-separator"><span></span></div>
                Standard Family Room
            </div>
            <div class="ajax-modal-photos-btn dynamic-gal" data-dynamicPath="[{'src': 'images/gal/slider/1.jpg'}, {'src': 'images/gal/slider/1.jpg'},{'src': 'images/gal/slider/1.jpg'}]">Photos (<span>3</span>)</div>
        </div>
        <div class="ajax-modal-list fl-wrap">
            <ul>
                <li>
                    <i class="fal fa-user-alt"></i>
                    <h5><span>3</span> Persons</h5>
                </li>
                <li>
                    <i class="fal fa-chalkboard"></i>
                    <h5><span>52</span> Ft²</h5>
                </li>
                <li>
                    <i class="fal fa-bath"></i>
                    <h5><span>1</span> Bathroom</h5>
                </li>
                <li>
                    <i class="fal fa-hand-holding-usd"></i>
                    <h5><span>81$</span> / Per Night</h5>
                </li>
            </ul>
        </div>
        <div class="ajax-modal-details fl-wrap">
            <!--ajax-modal-details-box-->
            <div class="ajax-modal-details-box">
                <h3>Details</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas in pulvinar neque. Nulla finibus lobortis pulvinar. Donec a consectetur nulla. Nulla posuere sapien vitae lectus suscipit, et pulvinar nisi tincidunt. Aliquam erat volutpat. Curabitur convallis fringilla diam sed aliquam. Sed tempor iaculis massa faucibus feugiat. In fermentum facilisis massa, a consequat purus viverra.</p>
            </div>
            <!--ajax-modal-details-box end-->
            <!--ajax-modal-details-box-->
            <div class="ajax-modal-details-box">
                <h3>Room Amenities</h3>
                <div class="listing-features fl-wrap">
                    <ul>
                        <li><i class="fal fa-wifi"></i> Free WiFi</li>
                        <li><i class="fas fa-glass-martini-alt"></i> Mini Bar</li>
                        <li><i class="fal fa-snowflake"></i>Air Conditioner</li>
                        <li><i class="fal fa-tv"></i><span>Tv Inside</li>
                        <li><i class="fal fa-concierge-bell"></i> Breakfast</li>
                        <li><i class="fal fa-paw"></i> Pet Friendly</li>
                    </ul>
                </div>
            </div>
            <!--ajax-modal-details-box end-->
            <a href="{% url 'main:booking-single'%}" class="btn float-btn color2-bg">Book Now<i class="fas fa-caret-right"></i></a>                            
        </div>
    </div>
    <!--ajax-modal-item-->
</div>
<!--ajax-modal-wrap end -->

{%  endblock %}

main/templates/rooms/room2.html
<!--ajax-modal-wrap -->
<div class="ajax-modal-wrap fl-wrap">
    <div class="ajax-modal-close"><i class="fal fa-times"></i></div>
    <!--ajax-modal-item-->
    <div class="ajax-modal-item fl-wrap">
        <div class="ajax-modal-media fl-wrap">
            <img src="images/gal/1.jpg" alt="">
            <div class="ajax-modal-title">
                <div class="section-title-separator"><span></span></div>
                Superior Double Room
            </div>
            <div class="ajax-modal-photos-btn dynamic-gal" data-dynamicPath="[{'src': 'images/gal/slider/1.jpg'}, {'src': 'images/gal/slider/1.jpg'},{'src': 'images/gal/slider/1.jpg'}]">Photos (<span>3</span>)</div>
        </div>
        <div class="ajax-modal-list fl-wrap">
            <ul>
                <li>
                    <i class="fal fa-user-alt"></i>
                    <h5><span>4</span> Persons</h5>
                </li>
                <li>
                    <i class="fal fa-chalkboard"></i>
                    <h5><span>72</span> Ft²</h5>
                </li>
                <li>
                    <i class="fal fa-bath"></i>
                    <h5><span>2</span> Bathroom</h5>
                </li>
                <li>
                    <i class="fal fa-hand-holding-usd"></i>
                    <h5><span>122$</span> / Per Night</h5>
                </li>
            </ul>
        </div>
        <div class="ajax-modal-details fl-wrap">
            <!--ajax-modal-details-box-->
            <div class="ajax-modal-details-box">
                <h3>Details</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas in pulvinar neque. Nulla finibus lobortis pulvinar. Donec a consectetur nulla. Nulla posuere sapien vitae lectus suscipit, et pulvinar nisi tincidunt. Aliquam erat volutpat. Curabitur convallis fringilla diam sed aliquam.  </p>
            </div>
            <!--ajax-modal-details-box end-->
            <!--ajax-modal-details-box-->
            <div class="ajax-modal-details-box">
                <h3>Room Amenities</h3>
                <div class="listing-features fl-wrap">
                    <ul>
                        <li><i class="fal fa-wifi"></i> Free WiFi</li>
                        <li><i class="fas fa-glass-martini-alt"></i> Mini Bar</li>
                        <li><i class="fal fa-snowflake"></i>Air Conditioner</li>
                        <li><i class="fal fa-tv"></i><span>Tv Inside</li>
                        <li><i class="fal fa-concierge-bell"></i> Breakfast</li>
                        <li><i class="fal fa-paw"></i> Pet Friendly</li>
                    </ul>
                </div>
            </div>
            <!--ajax-modal-details-box end-->
            <a href="{% url 'booking-single'%}" class="btn float-btn color2-bg">Book Now<i class="fas fa-caret-right"></i></a>                             
        </div>
    </div>
    <!--ajax-modal-item-->
</div>
<!--ajax-modal-wrap end -->

main/templates/rooms/room3.html
<!--ajax-modal-wrap -->
<div class="ajax-modal-wrap fl-wrap">
    <div class="ajax-modal-close"><i class="fal fa-times"></i></div>
    <!--ajax-modal-item-->
    <div class="ajax-modal-item fl-wrap">
        <div class="ajax-modal-media fl-wrap">
            <img src="images/gal/1.jpg" alt="">
            <div class="ajax-modal-title">
                <div class="section-title-separator"><span></span></div>
                Deluxe Single Room
            </div>
            <div class="ajax-modal-photos-btn dynamic-gal" data-dynamicPath="[{'src': 'images/gal/slider/1.jpg'}, {'src': 'images/gal/slider/1.jpg'},{'src': 'images/gal/slider/1.jpg'}]">Photos (<span>3</span>)</div>
        </div>
        <div class="ajax-modal-list fl-wrap">
            <ul>
                <li>
                    <i class="fal fa-user-alt"></i>
                    <h5><span>2</span> Persons</h5>
                </li>
                <li>
                    <i class="fal fa-chalkboard"></i>
                    <h5><span>102</span> Ft²</h5>
                </li>
                <li>
                    <i class="fal fa-bath"></i>
                    <h5><span>2</span> Bathroom</h5>
                </li>
                <li>
                    <i class="fal fa-hand-holding-usd"></i>
                    <h5><span>310$</span> / Per Night</h5>
                </li>
            </ul>
        </div>
        <div class="ajax-modal-details fl-wrap">
            <!--ajax-modal-details-box-->
            <div class="ajax-modal-details-box">
                <h3>Details</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas in pulvinar neque. Nulla finibus lobortis pulvinar. Donec a consectetur nulla. Nulla posuere sapien vitae lectus suscipit, et pulvinar nisi tincidunt. Aliquam erat volutpat. Curabitur convallis fringilla diam sed aliquam. Sed tempor iaculis massa faucibus feugiat. In fermentum facilisis massa, a consequat purus viverra.</p>
                <p> Nulla posuere sapien vitae lectus suscipit, et pulvinar nisi tincidunt. Aliquam erat volutpat. Curabitur convallis fringilla diam sed aliquam. Sed tempor iaculis massa faucibus feugiat. In fermentum facilisis massa, a consequat purus viverra.</p>
            </div>
            <!--ajax-modal-details-box end-->
            <!--ajax-modal-details-box-->
            <div class="ajax-modal-details-box">
                <h3>Room Amenities</h3>
                <div class="listing-features fl-wrap">
                    <ul>
                        <li><i class="fal fa-wifi"></i> Free WiFi</li>
                        <li><i class="fas fa-glass-martini-alt"></i> Mini Bar</li>
                        <li><i class="fal fa-snowflake"></i>Air Conditioner</li>
                        <li><i class="fal fa-tv"></i><span>Tv Inside</li>
                        <li><i class="fal fa-concierge-bell"></i> Breakfast</li>
                        <li><i class="fal fa-paw"></i> Pet Friendly</li>
                    </ul>
                </div>
            </div>
            <!--ajax-modal-details-box end-->
            <a href="{% url 'booking-single'%}" class="btn float-btn color2-bg">Book Now<i class="fas fa-caret-right"></i></a>                             
        </div>
    </div>
    <!--ajax-modal-item-->
</div>
<!--ajax-modal-wrap end -->