main/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from . import views

app_name = "main"

urlpatterns = [
    path("", views.home , name="home"),
    path("search-results", views.search, name="search"),
    path("term_condition", views.term_condition , name="term_condition"),
    path("police_prive", views.police_prive , name="police_prive"),


    path("index2", views.index2 , name="index2"),
    path("index3", views.index3 , name="index3"),
    path("index4", views.index4 , name="index4"),
    path("coming-soon", views.coming_soon , name="coming-soon"),
    path("about", views.about , name="about"),
    path("contacts", views.contacts , name="contacts"),
    path("author-single", views.authorsingle , name="author-single"),
    path("help", views.help , name="help"),
    path("pricing-tables", views.pricingtables , name="pricing-tables"),
    path("booking-single", views.bookingsingle , name="booking-single"),
    path("dashboard", views.dashboard , name="dashboard"),
    path("blog2", views.blog2 , name="blog2"),
    path("blog-single", views.blogsingle , name="blog-single"),
    path("dashboard-add-listing", views.dashboardaddlisting , name="dashboard-add-listing"),
    path("error-page", views.errorpage , name="error-page"),
    path("invoice", views.invoice , name="invoice"),
    path("blog", views.blog , name="blog"),
    path("listing-single", views.listingsingle , name="listing-single"),
    path("listing-single2", views.listingsingle2 , name="listing-single2"),
    path("listing-single3", views.listingsingle3 , name="listing-single3"),
    path("listing-single4", views.listingsingle4 , name="listing-single4"),
    path("listing", views.listing, name="listing"),
    path("listing2", views.listing2, name="listing2"),
    path("listing3", views.listing3, name="listing3"),
    path("listing4", views.listing4, name="listing4"),
    path("listing6", views.listing6, name="listing6"),
    path("room1", views.room1, name="room1"),
    path("room2", views.room2, name="room2"),
    path("room3", views.room3, name="room3"),
    path("dashboard-listing-table", views.dashboardlistingtable , name="dashboard-listing-table"),
    path("dashboard-password", views.dashboardpassword, name="dashboard-password"),
    path("dashboard-review", views.dashboardreview , name="dashboard-review"),
    path("dashboard-add-listing", views.dashboardaddlisting , name="dashboard-add-listing"),









   






   
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"

urlpatterns = [
    path("create/", views.RoomCreateView.as_view(), name="create"),
    path("host-list/", views.RoomHostListView.as_view(), name="host-list"),
    path("list/", views.RoomListView.as_view(), name="list"),
    path("<int:pk>", views.RoomDetailView.as_view(), name="detail"),
    path("<int:pk>/edit/", views.RoomUpdateView.as_view(), name="edit"),
    path("<int:pk>/delete", views.RoomDeleteView.as_view(), name="delete_room"),
    path('book-room/<int:pk>/', views.book_room, name='book_room'),

    path("<int:pk>/photo-list", views.RoomPhotosView.as_view(), name="photo-list"),
    path("<int:pk>/photos/add/", views.AddPhotoView.as_view(), name="add-photo"),
    path("<int:room_pk>/photos/<int:photo_pk>/delete/", views.delete_photo, name="delete-photo"),
    path("<int:room_pk>/photos/<int:photo_pk>/edit/", views.EditPhotoView.as_view(), name="edit-photo")
    
    # path("search/", views.search, name="search"),
]

sank/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from main import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns



def trigger_error(request):
    division_by_zero = 1 / 0



urlpatterns = [
    # path('admin/', admin.site.urls),
    path("", include("main.urls")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("lists/", include("lists.urls", namespace="lists")),
    path(os.environ.get("ADMIN_URL", "admin/"), admin.site.urls),
    path("sentry-debug/", trigger_error),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rooms/models.py
from django.utils import timezone
from django.db import models
from django.urls import reverse
from main import models as main_models
from calendar import Calendar


class AbstractItem(main_models.TimeStampedModel):
    name = models.CharField(max_length=500)

    class Meta:
        abstract = True

    def __str__(self):
        return self.name
    

class RoomType(AbstractItem):
    class Meta:
        verbose_name = "Room Type"


class Amenity(AbstractItem):
    class Meta:
        verbose_name_plural = "Amenities"


class Facility(AbstractItem):
    class Meta:
        verbose_name_plural = "Facilities"


class Reglement(AbstractItem):
    class Meta:
        verbose_name = "House Rule"


class Photo(main_models.TimeStampedModel):
    caption = models.CharField(max_length=80)
    file = models.ImageField(upload_to="room_photos")
    room = models.ForeignKey("Room", related_name="photos", on_delete=models.CASCADE)

    def __str__(self):
        return self.caption


class Room(main_models.TimeStampedModel):
    nom = models.CharField(max_length=140)
    description = models.TextField()
    prix_par_nuit = models.IntegerField(default=0)
    prix_par_semaine = models.IntegerField(default=0)
    prix_par_mois = models.IntegerField(default=0)
    caution = models.IntegerField(default=0)
    adresse = models.CharField(max_length=200)
    nombre_de_lits = models.IntegerField()
    nombre_de_chambres = models.IntegerField()
    nombre_de_douche = models.IntegerField()
    room_type = models.ForeignKey(
        "RoomType", related_name="rooms", on_delete=models.SET_NULL, null=True
    )
    agrement = models.ManyToManyField("Amenity", related_name="rooms", blank=True,)
    facilités = models.ManyToManyField("Facility", related_name="rooms", blank=True)
    reglements = models.ManyToManyField("Reglement", related_name="rooms", blank=True)

    video = models.URLField(blank=True, null=True)

    def __str__(self):
        return self.nom

    def save(self, *args, **kwargs):
        
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("rooms:detail", kwargs={"pk": self.pk})

    def total_rating(self):
        all_reviews = self.reviews.all()
        all_ratings = 0
        if len(all_reviews) > 0:
            for review in all_reviews:
                all_ratings += review.rating_average()
            return round(all_ratings / len(all_reviews), 2)
        return 0

    def first_photo(self):
        try:
            (photo,) = self.photos.all()[:1]
            return photo.file.url
        except ValueError:
            return None

    def get_next_four_photos(self):
        photos = self.photos.all()[1:20]
        return photos

   

rooms/forms.py
from django import forms
from django_countries.fields import CountryField
from . import models


class SearchForm(forms.Form):

   
    room_type = forms.ModelChoiceField(
        required=False, empty_label="Any kind", queryset=models.RoomType.objects.all()
    )
    prix_par_nuit = forms.IntegerField(required=False)
    prix_par_semaine = forms.IntegerField(required=False)
    prix_par_mois = forms.IntegerField(required=False)
    nombre_de_chambres = forms.IntegerField(required=False)
    nombre_de_lits = forms.IntegerField(required=False)
    nombre_de_douche = forms.IntegerField(required=False)
    agrement = forms.ModelMultipleChoiceField(
        required=False,
        queryset=models.Amenity.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )
    facilités = forms.ModelMultipleChoiceField(
        required=False,
        queryset=models.Facility.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )


class CreatePhotoForm(forms.ModelForm):
    class Meta:
        model = models.Photo
        fields = ("caption", "file")

    def save(self, pk, *args, **kwargs):
        photo = super().save(commit=False)
        room = models.Room.objects.get(pk=pk)
        photo.room = room
        photo.save()


class CreateRoomForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(CreateRoomForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "custom-form"
            visible.field.widget.attrs["placeholder"] = " "
        
    class Meta:
        model = models.Room
        fields = (
            "nom",
            "description",
            "prix_par_nuit",
            "prix_par_semaine",
            "prix_par_mois",
            "caution",
            "adresse",
            "nombre_de_lits",
            "nombre_de_chambres",
            "nombre_de_douche",
            "room_type",
            "agrement",
            "facilités",
            "reglements",
            "video",
        )
        labels = {
            "nom": "Titre",
            "description": "Description",
            "prix_par_nuit": "Prix par nuit (xof)",
            "prix_par_semaine": "Prix par semaine (xof)",
            "prix_par_mois": "Prix par mois (xof)",
            "caution":"Caution",
            "adresse": "Adresse",
            "agrement": "Commodités",
            "facilités": "Installations",
            "reglements": "règles de la maison",
            "nombre_de_lits": "Nombre de lits",
            "nombre_de_chambres": "chambres",
            "room_type": "Type",
            "video": "Vidéo de presentation",
            "nombre_de_douche": "Douches",

        }

    

rooms/views.py
from urllib.parse import urlencode
from django.http import Http404
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (
    TemplateView,
    CreateView,
    DetailView,
    UpdateView,
    DeleteView,
    ListView,
    FormView,
)
from rooms.forms import CreatePhotoForm, CreateRoomForm
from rooms.models import Room, Photo, RoomType
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.shortcuts import render, redirect, reverse








# -------------------------- ROOMS -------------------#

# CREATE
class RoomCreateView(LoginRequiredMixin, CreateView):
    model = Room
    form_class = CreateRoomForm
    template_name = "room_create.html"
    success_url = reverse_lazy("rooms:host-list")
    

    def form_valid(self, form):
        form.instance.host = self.request.user.client
        print("success")
        return super(RoomCreateView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(RoomCreateView, self).get_context_data(**kwargs)
        return context
    

# LIST
class RoomHostListView(ListView):
    model = Room
    context_object_name = "rooms"
    template_name = "room_list.html"
    

    def get_queryset(self):
        return Room.objects.filter(host=self.request.user.client).order_by(
            "-created"
        )

    def get_context_data(self, **kwargs):
        context = super(RoomHostListView, self).get_context_data(**kwargs)
        
        # Add the total_rooms count to the context
        context["total_rooms"] = Room.objects.filter(host=self.request.user.client).count()
        return context
    
    
class RoomListView(ListView):
    model = Room
    paginate_by = 30
    context_object_name = "rooms"
    template_name = "listing.html"
    

    def get_queryset(self):
        return Room.objects.all().order_by("-created")

    def get_context_data(self, **kwargs):
        context = super(RoomListView, self).get_context_data(**kwargs)
        return context



def room_category(request, slug):
    category = RoomType.objects.get(slug=slug)
    room = Room.objects.filter(room_type=category)


    return render(request, "room_category.html", locals())



# DETAIL
class RoomDetailView(DetailView):
    model = Room
    context_object_name = "room"
    template_name = "room_detail.html"

    


def book_room(request, pk):
    room_url = request.build_absolute_uri(reverse('rooms:detail', kwargs={'pk': pk}))
    message = f"Salut, je suis intéressé par cet appartement: {room_url}"
    
    # Define the recipient number
    recipient_number = '22893716116'  # Replace with the recipient's phone number
    
    # Construct the WhatsApp URL with recipient number and message
    whatsapp_params = {
        'text': message,
        'phone': recipient_number
    }
    whatsapp_url = f"https://api.whatsapp.com/send?{urlencode(whatsapp_params)}"
    
    return redirect(whatsapp_url)


# UPDATE
class RoomUpdateView(LoginRequiredMixin, UpdateView):
    model = Room
    form_class = CreateRoomForm
    template_name = "room_edit.html"
    success_url = reverse_lazy("rooms:host-list")
    

    def get_context_data(self, **kwargs):
        context = super(RoomUpdateView, self).get_context_data(**kwargs)
        return context
    

# DELETE
class RoomDeleteView(LoginRequiredMixin, DeleteView):
    model = Room
    success_url = reverse_lazy("rooms:host-list")
    template_name = "room_confirm_delete.html"

# -------------------------- ROOMS PHTOS -------------------#


class RoomPhotosView(LoginRequiredMixin, DetailView):

    model = Room
    template_name = "room_photo_list.html"

    def get_object(self, queryset=None):
        room = super().get_object(queryset=queryset)
        if room.host.pk != self.request.user.client.pk:
            raise Http404()
        return room


def delete_photo(request, room_pk, photo_pk):
    user = request.user.client
    try:
        room = Room.objects.get(pk=room_pk)
        if room.host.pk != user.pk:
            messages.error(request, "Can't delete that photo")
        else:
            Photo.objects.filter(pk=photo_pk).delete()
            messages.success(request, "Photo deleted")
        return redirect(reverse("rooms:photo-list", kwargs={"pk": room_pk}))
    except Room.DoesNotExist:
        return redirect(reverse("main:home"))


class EditPhotoView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = Photo
    template_name = "room_photo_edit.html"
    pk_url_kwarg = "photo_pk"
    success_message = "Photo Updated"
    fields = ("caption",)

    def get_success_url(self):
        room_pk = self.kwargs.get("room_pk")
        return reverse("rooms:photo-list", kwargs={"pk": room_pk})


class AddPhotoView(LoginRequiredMixin, FormView):

    template_name = "room_photo_create.html"
    fields = ("caption", "file")
    form_class = CreatePhotoForm

    def form_valid(self, form):
        pk = self.kwargs.get("pk")
        form.save(pk)
        messages.success(self.request, "Photo Uploaded")
        return redirect(reverse("rooms:photo-list", kwargs={"pk": pk}))

rooms/templates/listing.html

{% extends "index.html" %}
{% load static %}
{% load humanize %}
{% block content %}
            <!--  wrapper  -->
            <div id="wrapper">
                <!-- content-->
                <div class="content">
                    
                    <div class="breadcrumbs-fs fl-wrap">
                        <div class="container">
                            <div class="breadcrumbs fl-wrap"><a href="#">Accueil</a><a href="#">Listing </a><span>Fullwidth Map</span></div>
                        </div>
                    </div>
                    <!--section -->
                    <section class="grey-blue-bg small-padding">
                        <div class="container">
                            <div class="row">
                                <!--listing -->
                                <div class="col-md-12">
                                                   
                                    <!--col-list-wrap -->
                                    <div class="col-list-wrap fw-col-list-wrap">
                                        <!-- list-main-wrap-->
                                        <div class="list-main-wrap fl-wrap card-listing">
                                            <!-- list-main-wrap-opt-->
                                            <div class="list-main-wrap-opt fl-wrap">
                                                
                                                <!-- price-opt-->
                                                <div class="grid-opt">
                                                    <ul>
                                                        <li><span class="two-col-grid act-grid-opt"><i class="fas fa-th-large"></i></span></li>
                                                        <li><span class="one-col-grid"><i class="fas fa-bars"></i></span></li>
                                                    </ul>
                                                </div>
                                                <!-- price-opt end-->                               
                                            </div>
                                            <!-- list-main-wrap-opt end-->
                                            <!-- listing-item-container -->
                                            <div class="listing-item-container init-grid-items fl-wrap three-columns-grid">
                                                <!-- listing-item  -->
                                                {% for room in rooms %}
                                    <div class="listing-item">
                                        <article class="geodir-category-listing fl-wrap">
                                            <div class="geodir-category-img">
                                                <a href="{% url 'rooms:detail' room.id %}"><img
                                                        src="{{room.first_photo}}" alt=""></a>
                                                
                                                <!-- <div class="sale-window">Sale 20%</div> -->
                                                <div class="geodir-category-opt">
                                                    <div class="listing-rating card-popup-rainingvis"
                                                        data-starrating2="5"></div>
                                                    <div class="rate-class-name">
                                                        <div class="score"><strong>Very Good</strong>27 Reviews </div>
                                                        <span>5.0</span>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="geodir-category-content fl-wrap">
                                                <div class="geodir-category-content-title fl-wrap">
                                                    <div class="geodir-category-content-title-item">
                                                        <h3 class="title-sin_map"><a
                                                                href="{% url 'rooms:detail' room.id %}">{{room.name}}</a>
                                                        </h3>
                                                        <div class="geodir-category-location fl-wrap"><a href="#0"
                                                                class="map-item"><i
                                                                    class="fas fa-map-marker-alt"></i>{{room.city}}, {{room.country.name}} <br> {{room.address}}</a>
                                                        </div>
                                                    </div>
                                                </div>
                                                <p>{{room.description|truncatewords:10}}.</p>
                                                <ul class="facilities-list fl-wrap">
                                                    <li><i class="fal fa-wifi"></i><span>Free WiFi</span></li>
                                                    <li><i class="fal fa-parking"></i><span>Parking</span></li>
                                                    <li><i class="fal fa-smoking-ban"></i><span>Non-smoking Rooms</span>
                                                    </li>
                                                    <li><i class="fal fa-utensils"></i><span> Restaurant</span></li>
                                                </ul>
                                                <ul class="facilities-list fl-wrap">
                                                    <div class="geodir-category-price" style="font-size: 65%;">Prix/nuit<span> <br>  {{room.prix_par_nuit|intcomma}} F</span></div>
                                                    <div class="geodir-category-price" style="font-size: 65%;">Prix/semaine<span> <br>  {{room.prix_par_semaine|intcomma}} F</span></div>
                                                    <div class="geodir-category-price" style="font-size: 65%;">Prix/mois<span> <br>  {{room.prix_par_mois|intcomma}} F</span></div>
                                                </ul>
                                            </div>
                                        </article>
                                    </div>
                                    {% endfor %}
                                                                                              
                                                                                                         
                                                                     
                                            </div>
                                            <!-- listing-item-container end-->
                                            <!-- pagination-->
                                            <div class="pagination">
                                                <a href="#" class="prevposts-link"><i class="fa fa-caret-left"></i></a>
                                                <a href="#" >1</a>
                                                <a href="#" class="current-page">2</a>
                                                <a href="#">3</a>
                                                <a href="#">4</a>
                                                <a href="#" class="nextposts-link"><i class="fa fa-caret-right"></i></a>
                                            </div>
                                            <!-- pagination end-->
                                        </div>
                                        <!-- list-main-wrap end-->
                                    </div>
                                    <!--col-list-wrap end -->
                                </div>
                                <!--listing  end-->
                            </div>
                            <!--row end-->
                        </div>
                    </section>
                </div>
                <!-- content end-->
            </div>
            <!--wrapper end -->
 {% endblock %}

rooms/templates/room_list.html
{% extends "index.html" %}
{% load static %}
{% block content %}
            <!--  wrapper  -->
            <div id="wrapper">
                <!-- content-->
                <div class="content">
                    <!-- section-->
                    {% include 'dashboard/base.html' %}
                    <!-- section end-->
                    <!-- section-->
                    <section class="middle-padding">
                        <div class="container">
                            <!--dasboard-wrap-->
                            <div class="dasboard-wrap fl-wrap">
                                <!-- dashboard-content--> 
                                <div class="dashboard-content fl-wrap">
                                    <div class="dashboard-list-box fl-wrap">
                                        <div class="dashboard-header fl-wrap">
                                            <h3>Vos annonces</h3>
                                        </div>
                                        <!-- dashboard-list  -->
                                        {% for room in rooms  %}    
                                        <div class="dashboard-list">
                                            <div class="dashboard-message">
                                                <span class="new-dashboard-item">Nouvelle</span>
                                                <div class="dashboard-listing-table-image">
                                                    <a href="{% url 'rooms:detail' room.id %}"><img src="{{room.first_photo}}" alt=""></a>
                                                </div>
                                                <div class="dashboard-listing-table-text">
                                                    <h4><a href="{% url 'rooms:detail' room.id %}">{{room.name}}</a></h4>
                                                    <span class="dashboard-listing-table-address"><i class="far fa-map-marker"></i><a  href="#">{{room.address}}</a></span>
                                                    <ul class="dashboard-listing-table-opt  fl-wrap">
                                                        <li><a href="{% url 'rooms:edit' room.id %}">Modifier <i class="fal fa-edit"></i></a></li>
                                                        <li><a href="{% url 'rooms:photo-list' room.pk %}">photos <i class="fal fa-edit"></i></a></li>
                                                        <li><a href="{% url 'rooms:delete_room' room.id %}" class="del-btn">Supprimer <i class="fal fa-trash-alt"></i></a></li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                        {% endfor %}
                                        <!-- dashboard-list end-->    
                                        
                                    </div>
                                    <!-- pagination-->
                                    <div class="pagination">
                                        <a href="#" class="prevposts-link"><i class="fa fa-caret-left"></i></a>
                                        <a href="#">1</a>
                                        <a href="#" class="current-page">2</a>
                                        <a href="#">3</a>
                                        <a href="#">4</a>
                                        <a href="#" class="nextposts-link"><i class="fa fa-caret-right"></i></a>
                                    </div>
                                </div>
                                <!-- dashboard-list-box end--> 
                            </div>
                            <!-- dasboard-wrap end-->
                        </div>
                    </section>
                    <div class="limit-box fl-wrap"></div>
                </div>
                <!-- content end-->
            </div>
            <!--wrapper end -->
{% endblock %}

rooms/templates/room_photo_list.html
{% extends "index.html" %}
{% load static %}
{% block content %}
            <!--  wrapper  -->
            <div id="wrapper">
                <!-- content-->
                <div class="content">
                    <!-- section-->
                    {% include 'dashboard/base.html' %}
                    <!-- section end-->
                    <!-- section-->
                    <section class="middle-padding">
                        <div class="container">
                            <!--dasboard-wrap-->
                            <div class="dasboard-wrap fl-wrap">
                                <!-- dashboard-content--> 
                                <div class="dashboard-content fl-wrap">
                                    <div class="dashboard-list-box fl-wrap">
                                        <div class="dashboard-header fl-wrap">
                                            <h3>Photos ( total: {{room.photos.all.count}} )</h3>
                                        </div>
                                        <a href="{% url 'rooms:add-photo' pk=room.pk %}"><button type="submit" class="btn color2-bg float-btn">Ajouter<i
                                          class="fal fa-angle-double-up"></i></button></a>
                                        <!-- dashboard-list  -->
                                        {% for photo in room.photos.all %}
                                        <div class="dashboard-list">
                                            <div class="dashboard-message">
                                                <div class="dashboard-listing-table-image">
                                                  <img src="{{photo.file.url}}" alt="">
                                                </div>
                                                <div class="dashboard-listing-table-text">
                                                    <h4>{{photo.caption}}</h4>
                                                    <ul class="dashboard-listing-table-opt  fl-wrap">
                                                        <li><a href="{% url 'rooms:edit-photo' room.pk photo.pk %}">Modifier <i class="fal fa-edit"></i></a></li>
                                                        <li><a href="{% url 'rooms:delete-photo' room.pk photo.pk %}" class="del-btn">Supprimer <i class="fal fa-trash-alt"></i></a></li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                        {% endfor %}
                                        
                                        <!-- dashboard-list end-->    
                                        
                                    </div>
                                    
                                </div>
                                <!-- dashboard-list-box end--> 
                            </div>
                            <!-- dasboard-wrap end-->
                        </div>
                    </section>
                    <div class="limit-box fl-wrap"></div>
                </div>
                <!-- content end-->
            </div>
            <!--wrapper end -->
{% endblock %}