main/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from . import views

app_name = "main"

urlpatterns = [
    path("", views.home , name="home"),
    path("search-results", views.search, name="search"),
    path("term_condition", views.term_condition , name="term_condition"),
    path("police_prive", views.police_prive , name="police_prive"),


    path("index2", views.index2 , name="index2"),
    path("index3", views.index3 , name="index3"),
    path("index4", views.index4 , name="index4"),
    path("coming-soon", views.coming_soon , name="coming-soon"),
    path("about", views.about , name="about"),
    path("contacts", views.contacts , name="contacts"),
    path("author-single", views.authorsingle , name="author-single"),
    path("help", views.help , name="help"),
    path("pricing-tables", views.pricingtables , name="pricing-tables"),
    path("booking-single", views.bookingsingle , name="booking-single"),
    path("dashboard", views.dashboard , name="dashboard"),
    path("blog2", views.blog2 , name="blog2"),
    path("blog-single", views.blogsingle , name="blog-single"),
    path("dashboard-add-listing", views.dashboardaddlisting , name="dashboard-add-listing"),
    path("error-page", views.errorpage , name="error-page"),
    path("invoice", views.invoice , name="invoice"),
    path("blog", views.blog , name="blog"),
    path("listing-single", views.listingsingle , name="listing-single"),
    path("listing-single2", views.listingsingle2 , name="listing-single2"),
    path("listing-single3", views.listingsingle3 , name="listing-single3"),
    path("listing-single4", views.listingsingle4 , name="listing-single4"),
    path("listing", views.listing, name="listing"),
    path("listing2", views.listing2, name="listing2"),
    path("listing3", views.listing3, name="listing3"),
    path("listing4", views.listing4, name="listing4"),
    path("listing6", views.listing6, name="listing6"),
    path("room1", views.room1, name="room1"),
    path("room2", views.room2, name="room2"),
    path("room3", views.room3, name="room3"),
    path("dashboard-listing-table", views.dashboardlistingtable , name="dashboard-listing-table"),
    path("dashboard-password", views.dashboardpassword, name="dashboard-password"),
    path("dashboard-review", views.dashboardreview , name="dashboard-review"),
    path("dashboard-add-listing", views.dashboardaddlisting , name="dashboard-add-listing"),









   






   
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"

urlpatterns = [
    path("create/", views.RoomCreateView.as_view(), name="create"),
    path("host-list/", views.RoomHostListView.as_view(), name="host-list"),
    path("list/", views.RoomListView.as_view(), name="list"),
    path("<int:pk>", views.RoomDetailView.as_view(), name="detail"),
    path("<int:pk>/edit/", views.RoomUpdateView.as_view(), name="edit"),
    path("<int:pk>/delete", views.RoomDeleteView.as_view(), name="delete_room"),
    path('book-room/<int:pk>/', views.book_room, name='book_room'),

    path("<int:pk>/photo-list", views.RoomPhotosView.as_view(), name="photo-list"),
    path("<int:pk>/photos/add/", views.AddPhotoView.as_view(), name="add-photo"),
    path("<int:room_pk>/photos/<int:photo_pk>/delete/", views.delete_photo, name="delete-photo"),
    path("<int:room_pk>/photos/<int:photo_pk>/edit/", views.EditPhotoView.as_view(), name="edit-photo")
    
    # path("search/", views.search, name="search"),
]

sank/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from main import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns



def trigger_error(request):
    division_by_zero = 1 / 0



urlpatterns = [
    # path('admin/', admin.site.urls),
    path("", include("main.urls")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("lists/", include("lists.urls", namespace="lists")),
    path(os.environ.get("ADMIN_URL", "admin/"), admin.site.urls),
    path("sentry-debug/", trigger_error),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from . import managers


class TimeStampedModel(models.Model):

    """ Time Stamped Model """

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    objects = managers.CustomModelManager()

    class Meta:
        abstract = True

main/forms.py
# forms.py
from django import forms


class SearchForm(forms.Form):
    city = forms.CharField(required=False)
    guests = forms.IntegerField(required=False)
    check_in = forms.DateField(required=False)
    check_out = forms.DateField(required=False)

    

main/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from main.forms import SearchForm
from rooms.models import Room


# Create your views here.
def coming_soon(request):
    
    return render(request, "coming-soon.html")


def term_condition(request):
    
    return render(request, "term_&_condition.html")


def police_prive(request):
    
    return render(request, "police_prive.html")


def home(request):
    rooms = Room.objects.all().order_by("-created")[:9]
    
    return render(request, "index.html", locals())



def search(request):
    if request.method == 'GET':
        form = SearchForm(request.GET)
        if form.is_valid():
            room_type = form.cleaned_data.get('room_type')
            guests = form.cleaned_data.get('guests')
            when = form.cleaned_data.get('main-input-search')

            # Perform search logic for Room model
            rooms = Room.objects.all()
            if room_type:
                rooms = rooms.filter(room_type__name__icontains=room_type)
            if guests:
                rooms = rooms.filter(guests=guests)
            # Add more filtering logic as needed (e.g., when, check_out)

            

            return render(request, 'search_results.html', {
                'room_type': room_type,
                'rooms': rooms,
            })

    # If form is invalid or method is not GET
    return render(request, 'search_results.html')






def index2(request):
    
    return render(request, "index2.html")



def index3(request):
    
    return render(request, "index3.html")


def index4(request):
    
    return render(request, "index4.html")




def errorpage(request):
    
    return render(request, "404.html")


def about(request):
    
    return render(request, "about.html")


def contacts(request):
    
    return render(request, "contacts.html")


def invoice(request):
    
    return render(request, "invoice.html")


def authorsingle(request):
    
    return render(request, "author-single.html")


def help(request):
    
    return render(request, "help.html")


def pricingtables(request):
    
    return render(request, "pricing-tables.html")


def bookingsingle(request):
    
    return render(request, "booking-single.html")


def dashboard(request):
    
    return render(request, "dashboard.html")



def blog2(request):
    
    return render(request, "blog2.html")



def blogsingle(request):
    
    return render(request, "blog-single.html")


def dashboardaddlisting(request):
    
    return render(request, "dashboard-add-listing.html")



def blog(request):
    
    return render(request, "blog.html")


def listingsingle(request):
    
    return render(request, "listing-single.html")


def listingsingle2(request):
    
    return render(request, "listing-single2.html")


def listingsingle3(request):
    
    return render(request, "listing-single3.html")


def listingsingle4(request):
    
    return render(request, "listing-single4.html")


def listing(request):
    
    return render(request, "listing.html")


def listing2(request):
    
    return render(request, "listing2.html")


def listing3(request):
    
    return render(request, "listing3.html")


def listing4(request):
    
    return render(request, "listing4.html")


def listing5(request):
    
    return render(request, "listing5.html")


def listing6(request):
    
    return render(request, "listing6.html")


def room1(request):
    
    return render(request, "rooms/room1.html")


def room2(request):
    
    return render(request, "rooms/room2.html")


def room3(request):
    
    return render(request, "rooms/room3.html")

def dashboardaddlisting(request):
    
    return render(request, "dashboard-add-listing.html")


def dashboardlistingtable(request):
    
    return render(request, "dashboard-listing-table.html")


def dashboardpassword(request):
    
    return render(request, "dashboard-password.html")


def dashboardreview(request):
    
    return render(request, "dashboard-review.html")

main/templates/dashboard-password.html
{% extends "index.html" %}
{% load static %}
{% block content %}
            <!--  wrapper  -->
            <div id="wrapper">
                <!-- content-->
                <div class="content">
                    <!-- section-->
                    <section class="flat-header color-bg adm-header">
                        <div class="wave-bg wave-bg2"></div>
                        <div class="container">
                            <div class="dasboard-wrap fl-wrap">
                                <div class="dasboard-breadcrumbs breadcrumbs"><a href="#">Accueil</a><a href="#">Dashboard</a><span>Profile page</span></div>
                                <!--dasboard-sidebar-->
                                <div class="dasboard-sidebar">
                                    <div class="dasboard-sidebar-content fl-wrap">
                                        <div class="dasboard-avatar">
                                            <img src="images/avatar/1.jpg" alt="">
                                        </div>
                                        <div class="dasboard-sidebar-item fl-wrap">
                                            <h3>
                                                <span>Welcome </span>
                                                Jessie Manrty
                                            </h3>
                                        </div>
                                        <a href="{% url 'rooms:create'%}" class="ed-btn">Add Hotel</a>                                        
                                        <div class="user-stats fl-wrap">
                                            <ul>
                                                <li>
                                                    Listings	
                                                    <span>4</span>
                                                </li>
                                                <li>
                                                    Bookings
                                                    <span>32</span>	
                                                </li>
                                                <li>
                                                    Reviews	
                                                    <span>9</span>	
                                                </li>
                                            </ul>
                                        </div>
                                        <a href="#" class="log-out-btn color-bg">Log Out <i class="far fa-sign-out"></i></a>
                                    </div>
                                </div>
                                <!--dasboard-sidebar end--> 
                                <!-- dasboard-menu-->
                                <div class="dasboard-menu">
                                    <div class="dasboard-menu-btn color3-bg">Dashboard Menu <i class="fal fa-bars"></i></div>
                                    <ul class="dasboard-menu-wrap">
                                        <li>
                                            <a href="{% url 'main:dashboard'%}" class="user-profile-act"><i class="far fa-user"></i>Profile</a>
                                            <ul>
                                                <li><a href="">Edit profile</a></li>
                                                <li><a href="{% url 'main:dashboard-password'%}">Change Password</a></li>
                                            </ul>
                                        </li>
                                        <li><a href="{% url 'conversations:conversations'%}"><i class="far fa-envelope"></i> Messages <span>3</span></a></li>
                                        <li>
                                            <a href="{% url 'rooms:host-list'%}"><i class="far fa-th-list"></i> My listigs  </a>
                                            <ul>
                                                <li><a href="#">Active</a><span>5</span></li>
                                                <li><a href="#">Pending</a><span>2</span></li>
                                                <li><a href="#">Expire</a><span>3</span></li>
                                            </ul>
                                        </li>
                                        <li><a href="{% url 'reservations:bookings'%}"> <i class="far fa-calendar-check"></i> Bookings <span>2</span></a></li>
                                        <li><a href="{% url 'main:dashboard-review'%}"><i class="far fa-comments"></i> Reviews </a></li>
                                    </ul>
                                </div>
                                <!--dasboard-menu end-->
                                <!--Tariff Plan menu-->
                                <div   class="tfp-btn"><span>Tariff Plan : </span> <strong>Extended</strong></div>
                                <div class="tfp-det">
                                    <p>You Are on <a href="#">Extended</a> . Use link bellow to view details or upgrade. </p>
                                    <a href="#" class="tfp-det-btn color2-bg">Details</a>
                                </div>
                                <!--Tariff Plan menu end-->
                            </div>
                        </div>
                    </section>
                    <!-- section end-->
                    <!-- section-->
                    <section class="middle-padding">
                        <div class="container">
                            <!--dasboard-wrap-->
                            <div class="dasboard-wrap fl-wrap">
                                <!-- dashboard-content--> 
                                <div class="dashboard-content fl-wrap">
                                    <div class="box-widget-item-header">
                                        <h3> Change Password</h3>
                                    </div>
                                    <div class="custom-form no-icons">
                                        <div class="pass-input-wrap fl-wrap">
                                            <label>Current Password</label>
                                            <input type="password" class="pass-input" placeholder="" value=""/>
                                            <span class="eye"><i class="far fa-eye" aria-hidden="true"></i> </span>
                                        </div>
                                        <div class="pass-input-wrap fl-wrap">
                                            <label>New Password</label>
                                            <input type="password" class="pass-input" placeholder="" value=""/>
                                            <span class="eye"><i class="far fa-eye" aria-hidden="true"></i> </span>
                                        </div>
                                        <div class="pass-input-wrap fl-wrap">
                                            <label>Confirm New Password</label>
                                            <input type="password" class="pass-input" placeholder="" value=""/>
                                            <span class="eye"><i class="far fa-eye" aria-hidden="true"></i> </span>
                                        </div>
                                        <button class="btn  big-btn  color2-bg flat-btn float-btn">Save Changes<i class="fal fa-save"></i></button>
                                    </div>
                                </div>
                                <!-- dashboard-list-box end--> 
                            </div>
                            <!-- dasboard-wrap end-->
                        </div>
                    </section>
                    <div class="limit-box fl-wrap"></div>
                </div>
                <!-- content end-->
            </div>
            <!--wrapper end -->
{% endblock %}

main/templates/search_results.html
{% extends "index.html" %} {% load static %} {% block content %}

<!--  wrapper  -->
<div id="wrapper">
    <!-- content-->
    <div class="content">
        <div class="breadcrumbs-fs fl-wrap">
            <div class="container">
                <div class="breadcrumbs fl-wrap">
                    <a href="#">Accueil</a><a href="#">Listings</a><span>Listings Without Map</span>
                </div>
            </div>
        </div>
        <!--section -->
        <section class="grey-blue-bg small-padding" id="sec1">
            <div class="container">
                <div class="row">
                    <!--listing -->
                    <div class="col-md-12">
                        <div class="mobile-list-controls fl-wrap mar-bot-cont">
                            <div class="mlc show-list-wrap-search fl-wrap">
                                <i class="fal fa-filter"></i> Filter
                            </div>
                        </div>
                        <!--list-wrap-search   -->

                        <!--list-wrap-search end -->
                        <!--col-list-wrap -->
                        <div class="col-list-wrap fw-col-list-wrap">
                            <!-- list-main-wrap-->
                            <div class="list-main-wrap fl-wrap card-listing">
                                <!-- list-main-wrap-opt-->
                                <div class="list-main-wrap-opt fl-wrap">
                                    <div class="list-main-wrap-title fl-wrap col-title">
                                        <h2>Resultats Pour : <span>{{room_type}} </span></h2>
                                    </div>
                                   
                                </div>
                                <!-- list-main-wrap-opt end-->
                                <!-- listing-item-container -->
                                <div class="listing-item-container init-grid-items fl-wrap three-columns-grid">
                                    <!-- listing-item  -->
                                    {% for room in rooms %}
                                    <div class="listing-item">
                                        <article class="geodir-category-listing fl-wrap">
                                            <div class="geodir-category-img">
                                                <a href="{% url 'rooms:detail' room.id %}"><img
                                                        src="{{room.first_photo}}" alt="" /></a>
                                                <div class="listing-avatar">
                                                    <a href="{% url 'main:author-single' %}"><img
                                                            src="{% if room.host.avatar %}{{room.host.avatar.url}}{% else %}{% static 'images/avatar/1.jpg' %}{% endif %}" alt="" /></a>
                                                    <span class="avatar-tooltip">Ajouté par
                                                        <strong>{{room.host}}</strong></span>
                                                </div>
                                                <div class="sale-window">Sale 20%</div>
                                                <div class="geodir-category-opt">
                                                    <div class="listing-rating card-popup-rainingvis"
                                                        data-starrating2="5"></div>
                                                    <div class="rate-class-name">
                                                        <div class="score">
                                                            <strong>Very Good</strong>27 Reviews
                                                        </div>
                                                        <span>5.0</span>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="geodir-category-content fl-wrap">
                                                <div class="geodir-category-content-title fl-wrap">
                                                    <div class="geodir-category-content-title-item">
                                                        <h3 class="title-sin_map">
                                                            <a href="{% url 'rooms:detail' room.id %}">{{room.name}}</a>
                                                        </h3>
                                                        <div class="geodir-category-location fl-wrap">
                                                            <a href="#0" class="map-item"><i
                                                                    class="fas fa-map-marker-alt"></i>{{room.city}}, {{room.country.name}} <br> {{room.address}}</a>
                                                        </div>
                                                    </div>
                                                </div>
                                                <p>{{room.description|truncatewords:10}}.</p>
                                                <ul class="facilities-list fl-wrap">
                                                    <li>
                                                        <i class="fal fa-wifi"></i><span>Free WiFi</span>
                                                    </li>
                                                    <li>
                                                        <i class="fal fa-parking"></i><span>Parking</span>
                                                    </li>
                                                    <li>
                                                        <i class="fal fa-smoking-ban"></i><span>Non-smoking Rooms</span>
                                                    </li>
                                                    <li>
                                                        <i class="fal fa-utensils"></i><span> Restaurant</span>
                                                    </li>
                                                </ul>
                                                <div class="geodir-category-footer fl-wrap">
                                                    <div class="geodir-category-price">
                                                        Prix/Nuit <span>{{room.price}} F</span>
                                                    </div>
                                                    <div class="geodir-opt-list">
                                                        <a href="#0" class="map-item"><i
                                                                class="fal fa-map-marker-alt"></i><span
                                                                class="geodir-opt-tooltip">On the map
                                                                <strong>1</strong></span></a>
                                                        <a href="#" class="geodir-js-favorite"><i
                                                                class="fal fa-heart"></i><span
                                                                class="geodir-opt-tooltip">Save</span></a>
                                                        <a href="#" class="geodir-js-booking"><i
                                                                class="fal fa-exchange"></i><span
                                                                class="geodir-opt-tooltip">Find Directions</span></a>
                                                    </div>
                                                </div>
                                            </div>
                                        </article>
                                    </div>
                                    {% endfor %}
                                    <!-- listing-item end -->
                                </div>
                                <!-- listing-item-container end-->
                                <!-- pagination-->
                                <div class="pagination">
                                    <a href="#" class="prevposts-link"><i class="fa fa-caret-left"></i></a>
                                    <a href="#">1</a>
                                    <a href="#" class="current-page">2</a>
                                    <a href="#">3</a>
                                    <a href="#">4</a>
                                    <a href="#" class="nextposts-link"><i class="fa fa-caret-right"></i></a>
                                </div>
                                <!-- pagination end-->
                            </div>
                            <!-- list-main-wrap end-->
                        </div>
                        <!--col-list-wrap end -->
                    </div>
                    <!--listing  end-->
                    
                </div>
                
                <!--row end-->

               
            </div>
        </section>
        <!--section end -->
    </div>
    <!-- content end-->
</div>
<!--wrapper end -->

{% endblock %}